### ISSUE TITLE
Unable to setup job

### ISSUE THREAD

**Issue by tmonck** [tecosaur/org-tangle-action#2]
![image](https://user-images.githubusercontent.com/3812050/152575987-13ed7c44-0799-400c-93f8-0a19b8db19d3.png)
This is the error I get when referencing this particular action. I have been able to use https://github.com/tecosaur/org-knit-action so not sure what's different here. 

My yml looks like:
```yml
name: Generate Helper Scripts
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - name: Org Tangle
        uses: tecosaur/org-tangle-action@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Update the branch with the newly tangled scripts
          branch: ${{ github.ref }}
```
